  RootNode:
    BaseYaml: ../../CommonForms/PetraFormDialog.yaml
    FormTitle: Intranet Export Settings
    Namespace: Ict.Petra.Client.MSysMan.Gui
    FormType: dialog
    Template: window
    WindowWidth: 350
    WindowHeight:260

    Controls:
        pnlDialogContent:
            Controls: [grpGeneral, grpPassword]
        grpGeneral:
            Controls: [txtDonationDays, txtOptionalMetadata, txtReplyToEmail]
            Stretch: horizontally
        txtDonationDays:
            Width: 40
            Format: Integer
        txtOptionalMetadata:
            Stretch: horizontally
        txtReplyToEmail:
            Stretch: horizontally
        grpPassword:
            Controls: [txtOldPassword, txtNewPassword, txtConfirmPassword]
            Stretch: horizontally
        txtOldPassword:
            Stretch: horizontally
            PasswordEntry: true
        txtNewPassword:
            Stretch: horizontally
            PasswordEntry: true
        txtConfirmPassword:
            Stretch: horizontally
            PasswordEntry: true