RootNode:
    BaseYaml: ../../../CommonForms/PetraFormDialog.yaml
    FormTitle: Ledger Settings
    UtilObjectClass: TFrmPetraEditUtils
    InterfaceName: IFrmPetraEdit
    Namespace: Ict.Petra.Client.MFinance.Gui.Setup
    UsingNamespaces: [Ict.Petra.Shared.MFinance.Account.Data, Ict.Petra.Shared.MFinance.GL.Data, Ict.Petra.Shared.MFinance.Account.Validation]
    DatasetType: Ict.Petra.Shared.MFinance.GL.Data.GLSetupTDS
    MasterTable: ALedger
    FormType: dialog
    Template: windowEdit
    WindowWidth: 580
    WindowHeight: 600
    Actions:
        actApply: {ActionClick: BtnApply_Click}
        actTabChange: {ActionClick: OnTabChange}
    Controls:
        pnlDialogContent:
            Padding: 4,0,8,0
            Dock: Fill
            Controls: [tabAllSettings]
            
        tabAllSettings: {Action=actTabChange}
            Controls: [tpgLedger, tpgAccountsPayable]
            Dock: Fill
            Action:actTabChange
        tpgLedger:
            Controls: [ucoGeneralLedgerSettings]
        tpgAccountsPayable:
            Controls: [ucoAPLedgerSettings]
        ucoGeneralLedgerSettings:
            Type: Ict.Petra.Client.MFinance.Gui.Setup.TUC_GeneralLedgerSettings
            Dock: Fill
        ucoAPLedgerSettings:
            Type: Ict.Petra.Client.MFinance.Gui.Setup.TUC_APLedgerSettings
            Dock: Fill
        btnApply: {Visible=true}
